version: 0.2

phases:
  build:
    commands:
      # Listar e pegar o primeiro ID do launch template
      - LAUNCH_TEMPLATE_ID=$(aws ec2 describe-launch-templates --query 'LaunchTemplates[0].LaunchTemplateId' --output text)      
      # Listar todas as versões do launch template e extrair números de versão
      - version_numbers=$(aws ec2 describe-launch-template-versions --launch-template-id $LAUNCH_TEMPLATE_ID --query 'LaunchTemplateVersions[*].VersionNumber' --output text)
      # Encontrar o número máximo entre os números de versão
      - max_version=$(echo "$version_numbers" | tr '\t' '\n' | sort -nr | head -n 1)
      # Número máximo
      - Latest=$((max_version))
      - Latest_NEW=$((max_version + 1))
      - echo "$LAUNCH_TEMPLATE_ID" > info.txt

      # Encontrar o ID do grupo de segurança chamado "web"
      - SECURITY_GROUP_ID=$(aws ec2 describe-security-groups --filters Name=group-name,Values=web --query 'SecurityGroups[0].GroupId' --output text)
      # Iniciar uma instância EC2
      - aws ec2 run-instances --image-id ami-080e1f13689e07408 --instance-type t2.micro --subnet-id 'subnet-08153eb51832aa705' --security-group-ids $SECURITY_GROUP_ID --user-data '#!/bin/bash\napt-get update -y\napt-get install -y nginx git\ngit config --global user.name "ubuntu"\ngit config --global user.email "ubuntu@email.com"\ngit clone https://github.com/zedmaster/coodesh.git\ncp -R coodesh/app/* /var/www/html/\nservice nginx restart\nwget https://aws-codedeploy-us-east-1.s3.amazonaws.com/latest/install \nchmod +x install \n./install auto \nservice codedeploy-agent status' > instance_output.json
      # Extrair o ID da instância criada
      - INSTANCE_ID=$(jq -r '.Instances[0].InstanceId' instance_output.json)
      # Esperar até que a instância esteja em execução
      - aws ec2 wait instance-running --instance-ids $INSTANCE_ID
      # Criar uma AMI da instância
      - AMI_ID=$(aws ec2 create-image --instance-id $INSTANCE_ID --name "$INSTANCE_ID-V$Latest_NEW" --no-reboot --output text)
      # Esperar até que a AMI esteja disponível
      - aws ec2 wait image-available --image-ids $AMI_ID
      # Excluir a instância
      - aws ec2 terminate-instances --instance-ids $INSTANCE_ID


      
      
      # Criar uma nova versão do launch template modificando o image_id
      - |
        LAUNCH_TEMPLATE_DATA='{"ImageId": "'$AMI_ID'"}'
        aws ec2 create-launch-template-version --launch-template-id $LAUNCH_TEMPLATE_ID --source-version $Latest --launch-template-data "$LAUNCH_TEMPLATE_DATA"

artifacts:
  files: info.txt